version: '3.9'

networks:
  codeigniter_network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80" # Map container's port 80 (Apache) to host's port 8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      CI_ENVIRONMENT: development
      DB_HOST: db # Use the service name as the hostname
      DB_DATABASE: finalproyektst
      DB_USERNAME: postgres
      DB_PASSWORD: raihan
    networks:
      - codeigniter_network # Attach to the custom network

  db:
    image: postgres:latest
    container_name: codeigniter_db
    environment:
      POSTGRES_DB: finalproyektst
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raihan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codeigniter_network # Attach to the custom network

volumes:
  postgres_data:
